PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX sc: <http://iiif.io/api/presentation/2#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX cidoc: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT *

WHERE {
  ?s a cidoc:E22_Man-Made_Object ;
     cidoc:P129i_is_subject_of [
      sc:hasSequences/rdf:rest*/rdf:first [
    		sc:hasCanvases/rdf:rest*/rdf:first [
          		sc:hasImageAnnotations/rdf:rest*/rdf:first [
            			oa:hasBody ?body
        		]
      		]
    	]
  	]
}
