FROM debian

RUN apt update && apt install -y wget build-essential python-dev libagg-dev libpotrace-dev pkg-config potrace imagemagick python3-pip
RUN wget https://www.dropbox.com/s/04suaimdpru76h3/ArtLine_920.pkl

COPY . /workspace/coghent
RUN pip install -r /workspace/coghent/requirements.txt
#VOLUME .:/workspace/coghent_results
ENTRYPOINT ["python3"]
CMD ["/workspace/coghent/artlineflow.py"]